stages:
  - analysis
  - build
  - test

.common:
  variables:
    LIBTRACK_PROJECT_REF: leap-v5-platform/libtrack
    LIBTRACK_REF: v5.13.2

python-black:
  stage: analysis
  image: registry.ultrahaptics.com/leap-v5-platform/infrastructure/x64_linux_toolchain:v3.16.4
  allow_failure: false
  tags:
    - docker
  interruptible: true
  needs: [ ]
  script:
    - python3 -m venv python_env --system-site-packages
    - python_env/bin/python -m pip install black==22.3.0
    - python_env/bin/python -m black --diff --check examples src

MacOSBuild:
  extends: .common
  stage: build
  tags:
    - platform-macm1
  before_script:
    - pkgutil --expand-full $CI_PROJECT_DIR/Ultraleap-Hand-Tracking*.pkg $CI_PROJECT_DIR/unpack
  script:
    - export LEAP_SDK_INSTALL_LOCATION="$CI_PRIJECT_DIR/Ultraleap-Hand-Tracking.pkg/Payload/Library/Application Support/Ultraleap/LeapSDK"
    - mkdir build
    - python3 -m venv build/venv --system-site-packages
    - build/venv/bin/python -m pip install -r requirements.txt
    - build/venv/bin/python -m build -o build/dist
  needs:
    - project: $LIBTRACK_PROJECT_REF
      job: MacOSX64RelDebProd-LTS
      ref: $LIBTRACK_REF
      artifacts: true
